/**
 * @fileoverview Tool definition for fetching USGS pre-computed real-time earthquake feeds.
 * @module mcp-server/tools/definitions/earthquake-get-feed.tool
 */

import { tool, z } from '@cyanheads/mcp-ts-core';
import { JsonRpcErrorCode, McpError } from '@cyanheads/mcp-ts-core/errors';
import { EarthquakeEventSchema, formatEvent } from '@/mcp-server/tools/schemas.js';
import { getUsgsService } from '@/services/usgs/usgs-service.js';

export const earthquakeGetFeed = tool('earthquake_get_feed', {
  title: 'Get USGS Earthquake Feed',
  description:
    'Fetch a USGS pre-computed real-time earthquake feed by magnitude tier and time window. ' +
    'These feeds are CDN-cached by USGS and faster and more available than the query API — ' +
    'use them for "what\'s happening now" queries. ' +
    '"all" includes microseisms (M<1); "significant" is a USGS curation based on magnitude, ' +
    'felt reports, and PAGER impact estimates. ' +
    '"hour" returns 0–10 events typically; "month" can exceed 10,000 for the "all" tier. ' +
    'For historical or filtered queries, use earthquake_search instead.',
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },

  input: z.object({
    magnitude_tier: z
      .enum(['all', '1.0', '2.5', '4.5', 'significant'])
      .default('2.5')
      .describe(
        'Minimum magnitude threshold for the feed. ' +
          '"all" includes microseisms (M<1). ' +
          '"1.0" is M1.0+. "2.5" is M2.5+. "4.5" is M4.5+. ' +
          '"significant" is a USGS curated selection based on magnitude, felt reports, and PAGER impact estimates — not purely magnitude-based.',
      ),
    time_window: z
      .enum(['hour', 'day', 'week', 'month'])
      .default('day')
      .describe(
        'Time window for the feed. ' +
          '"hour" typically returns 0–10 events; "month" can exceed 10,000 for the "all" tier. ' +
          'Prefer "hour" or "day" for real-time status checks.',
      ),
  }),

  output: z.object({
    count: z.number().describe('Number of events in the feed.'),
    generated_at: z
      .string()
      .describe('ISO 8601 UTC timestamp when this feed was generated by USGS.'),
    events: z
      .array(EarthquakeEventSchema.describe('A single earthquake event.'))
      .describe('Earthquake events, newest first.'),
    feed_url: z.string().describe('Source feed URL.'),
  }),

  // Agent-facing context for empty-feed windows — a notice so structuredContent-only
  // clients see recovery guidance without parsing format() text.
  enrichment: {
    notice: z
      .string()
      .optional()
      .describe(
        'Recovery guidance when the feed contains no events — suggests narrowing the magnitude tier, ' +
          'widening the time window, or using earthquake_search for filtered queries. ' +
          'Absent when the feed contains events.',
      ),
  },

  errors: [
    {
      reason: 'feed_unavailable',
      code: JsonRpcErrorCode.ServiceUnavailable,
      when: 'USGS feed endpoint returns non-2xx or times out.',
      recovery: 'Try a smaller time_window, or use earthquake_search as a fallback.',
    },
  ],

  async handler(input, ctx) {
    ctx.log.info('Fetching USGS feed', {
      magnitude_tier: input.magnitude_tier,
      time_window: input.time_window,
    });

    let result: Awaited<ReturnType<typeof getUsgsService.prototype.getFeed>>;
    try {
      result = await getUsgsService().getFeed(input.magnitude_tier, input.time_window, ctx);
    } catch (err) {
      if (err instanceof McpError && err.code === JsonRpcErrorCode.ServiceUnavailable) {
        throw ctx.fail('feed_unavailable', err.message, {
          ...ctx.recoveryFor('feed_unavailable'),
        });
      }
      throw err;
    }

    ctx.log.info('Feed fetched', {
      count: result.count,
      magnitude_tier: input.magnitude_tier,
      time_window: input.time_window,
    });

    if (result.count === 0) {
      ctx.enrich.notice(
        `No events in the ${input.magnitude_tier}/${input.time_window} feed. ` +
          'Try a wider time_window (e.g. "day" or "week"), a lower magnitude_tier (e.g. "1.0" or "all"), ' +
          'or use earthquake_search for filtered historical queries.',
      );
    }

    return {
      count: result.count,
      generated_at: result.generatedAt,
      events: result.events,
      feed_url: result.feedUrl,
    };
  },

  format: (result) => {
    const lines: string[] = [
      `**Feed:** ${result.feed_url}`,
      `**Generated:** ${result.generated_at} | **Count:** ${result.count}`,
      '',
    ];

    if (result.count === 0) {
      lines.push('_No events in this feed window._');
    } else {
      for (const event of result.events) {
        lines.push(...formatEvent(event));
        lines.push('');
      }
    }

    return [{ type: 'text', text: lines.join('\n') }];
  },
});
