/**
 * @fileoverview Tool definition for fetching USGS pre-computed real-time earthquake feeds.
 * @module mcp-server/tools/definitions/earthquake-get-feed.tool
 */

import { tool, z } from '@cyanheads/mcp-ts-core';
import { JsonRpcErrorCode, McpError } from '@cyanheads/mcp-ts-core/errors';
import { paginateArray } from '@cyanheads/mcp-ts-core/utils';
import { EarthquakeEventSchema, formatEvent } from '@/mcp-server/tools/schemas.js';
import { getUsgsService, type UsgsService } from '@/services/usgs/usgs-service.js';

/** Events returned per call when the caller does not set limit. */
const DEFAULT_PAGE_SIZE = 100;
/** Upper bound on events per call, matching the limit input's maximum. */
const MAX_PAGE_SIZE = 1000;

export const earthquakeGetFeed = tool('earthquake_get_feed', {
  title: 'Get USGS Earthquake Feed',
  description:
    'Fetch a USGS pre-computed real-time earthquake feed by magnitude tier and time window. ' +
    'These feeds are CDN-cached by USGS and faster and more available than the query API — ' +
    'use them for "what\'s happening now" queries. ' +
    '"all" includes microseisms (M<1); "significant" is a USGS curation based on magnitude, ' +
    'felt reports, and PAGER impact estimates. ' +
    '"hour" returns 0–10 events typically; "month" can exceed 10,000 for the "all" tier, ' +
    'so results are returned a page at a time: count is the page size, totalCount the whole feed, ' +
    'and nextCursor the input for the following page. ' +
    'The cursor is opaque and must be passed back verbatim — unlike earthquake_search, these feeds ' +
    'have no upstream paging parameter and USGS regenerates them about once a minute, so a numeric ' +
    'offset across two calls would skip or repeat events. ' +
    'For historical or filtered queries, use earthquake_search instead.',
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },

  input: z.object({
    magnitude_tier: z
      .enum(['all', '1.0', '2.5', '4.5', 'significant'])
      .default('2.5')
      .describe(
        'Minimum magnitude threshold for the feed. ' +
          '"all" includes microseisms (M<1). ' +
          '"1.0" is M1.0+. "2.5" is M2.5+. "4.5" is M4.5+. ' +
          '"significant" is a USGS curated selection based on magnitude, felt reports, and PAGER impact estimates — not purely magnitude-based.',
      ),
    time_window: z
      .enum(['hour', 'day', 'week', 'month'])
      .default('day')
      .describe(
        'Time window for the feed. ' +
          '"hour" typically returns 0–10 events; "month" can exceed 10,000 for the "all" tier. ' +
          'Prefer "hour" or "day" for real-time status checks.',
      ),
    limit: z
      .number()
      .int()
      .min(1)
      .max(MAX_PAGE_SIZE)
      .optional()
      .describe(
        `Maximum events to return in this call. Default ${DEFAULT_PAGE_SIZE}, max ${MAX_PAGE_SIZE}. ` +
          'Applies to the first page; later pages carry the page size inside the cursor, so set it ' +
          'on the first call rather than changing it mid-sequence.',
      ),
    cursor: z
      .string()
      .optional()
      .describe(
        "Opaque token for the next page, taken verbatim from a previous call's nextCursor. " +
          'Omit for the first page. Do not construct, parse, or edit it — it encodes a position ' +
          'in the feed snapshot and is rejected if malformed.',
      ),
  }),

  output: z.object({
    count: z.number().describe('Number of events returned in this page, not the whole feed.'),
    generated_at: z
      .string()
      .describe('ISO 8601 UTC timestamp when this feed was generated by USGS.'),
    events: z
      .array(EarthquakeEventSchema.describe('A single earthquake event.'))
      .describe('Earthquake events for this page, newest first.'),
    feed_url: z.string().describe('Source feed URL.'),
  }),

  // Agent-facing context for empty-feed windows and paging state — notices and page
  // metadata reach structuredContent and content[] without parsing format() text.
  enrichment: {
    totalCount: z
      .number()
      .optional()
      .describe('Number of events in the whole feed, across every page.'),
    truncated: z
      .boolean()
      .optional()
      .describe(
        'True when the feed holds more events than this page returned. ' +
          'nextCursor carries the input for the following page.',
      ),
    nextCursor: z
      .string()
      .optional()
      .describe(
        'Opaque token to pass back as the cursor input for the next page. ' +
          'Present only when more events remain; absent means this was the last page.',
      ),
    notice: z
      .string()
      .optional()
      .describe(
        'Recovery guidance when the feed contains no events, or how to continue when a page was ' +
          'capped — narrowing the magnitude tier, widening the time window, paging with the ' +
          'cursor, or using earthquake_search for filtered queries. ' +
          'Absent when a single page covers the whole feed.',
      ),
  },

  errors: [
    {
      reason: 'feed_unavailable',
      code: JsonRpcErrorCode.ServiceUnavailable,
      when: 'USGS feed endpoint returns a 5xx, HTML, or is unreachable.',
      retryable: true,
      recovery: 'Try a smaller time_window, or use earthquake_search as a fallback.',
    },
    {
      reason: 'feed_timeout',
      code: JsonRpcErrorCode.Timeout,
      when: 'USGS feed endpoint did not answer before the request deadline.',
      retryable: true,
      recovery:
        'Retry the call, or request a smaller time_window — the "month" and "all" feeds are ' +
        'the largest documents and the slowest to transfer.',
    },
  ],

  async handler(input, ctx) {
    ctx.log.info('Fetching USGS feed', {
      magnitude_tier: input.magnitude_tier,
      time_window: input.time_window,
      limit: input.limit,
      paged: input.cursor != null,
    });

    let result: Awaited<ReturnType<UsgsService['getFeed']>>;
    try {
      result = await getUsgsService().getFeed(input.magnitude_tier, input.time_window, ctx);
    } catch (err) {
      if (err instanceof McpError && err.code === JsonRpcErrorCode.ServiceUnavailable) {
        throw ctx.fail('feed_unavailable', err.message, {
          ...ctx.recoveryFor('feed_unavailable'),
        });
      }
      // A timeout classifies as Timeout, not ServiceUnavailable — it needs its own
      // branch or it bypasses the contract and reaches the caller with no recovery hint.
      if (err instanceof McpError && err.code === JsonRpcErrorCode.Timeout) {
        throw ctx.fail('feed_timeout', err.message, {
          ...ctx.recoveryFor('feed_timeout'),
        });
      }
      throw err;
    }

    ctx.log.info('Feed fetched', {
      count: result.count,
      magnitude_tier: input.magnitude_tier,
      time_window: input.time_window,
    });

    // USGS serves the feed as one precomputed document with no upstream paging
    // parameter, so a page is a slice of the array already in memory — the shape
    // paginateArray's opaque cursor is built for. `Context extends RequestContext`,
    // so the handler ctx goes in directly: a cursor rejection can only come from this
    // call site, and a separate label would name nothing `ctx.operation` does not.
    const page = paginateArray(
      result.events,
      input.cursor,
      input.limit ?? DEFAULT_PAGE_SIZE,
      MAX_PAGE_SIZE,
      ctx,
    );

    const totalCount = result.events.length;
    ctx.enrich({ totalCount });
    if (page.nextCursor != null) {
      ctx.enrich({ truncated: true, nextCursor: page.nextCursor });
    }

    if (totalCount === 0) {
      ctx.enrich.notice(
        `No events in the ${input.magnitude_tier}/${input.time_window} feed. ` +
          'Try a wider time_window (e.g. "day" or "week"), a lower magnitude_tier (e.g. "1.0" or "all"), ' +
          'or use earthquake_search for filtered historical queries.',
      );
    } else if (page.items.length === 0) {
      ctx.enrich.notice(
        'No events at this cursor — the previous page was the last one. ' +
          'Start over without a cursor to re-read the feed from the beginning.',
      );
    } else if (page.nextCursor != null) {
      ctx.enrich.notice(
        `Showing ${page.items.length} of ${totalCount} events in the ` +
          `${input.magnitude_tier}/${input.time_window} feed. ` +
          'Call again with the nextCursor value as cursor for the following page, ' +
          'or narrow magnitude_tier or time_window for a smaller feed.',
      );
    }

    return {
      count: page.items.length,
      generated_at: result.generatedAt,
      events: page.items,
      feed_url: result.feedUrl,
    };
  },

  format: (result) => {
    const lines: string[] = [
      `**Feed:** ${result.feed_url}`,
      `**Generated:** ${result.generated_at} | **Count:** ${result.count}`,
      '',
    ];

    if (result.count === 0) {
      lines.push('_No events in this feed window._');
    } else {
      for (const event of result.events) {
        lines.push(...formatEvent(event));
        lines.push('');
      }
    }

    return [{ type: 'text', text: lines.join('\n') }];
  },
});
